import numpy as np

def simulate_nozzle_expansion(
    P_inlet,     # Pressure before nozzle (Pascals)
    P_outlet,    # Pressure at channel (Pascals)
    T_exhaust,   # Server exhaust temperature (C)
    throat_diam  # Throat diameter (meters)
):
    # Convert temperature to Kelvin
    T0 = T_exhaust + 273.15
    
    # Specific heat ratio for low-boiling 
    # organic driver fluid proxy (gamma)
    gamma = 1.15 
    
    # Specific gas constant proxy (J/kg*K)
    R_fluid = 240.0
    
    # Calculate critical pressure ratio 
    # to test for choked flow conditions
    crit_ratio = (
        (2.0 / (gamma + 1.0)) ** (gamma / (gamma - 1.0))
    )
    
    actual_ratio = P_outlet / P_inlet

    # If the pressure drop is sufficient,
    # the nozzle will choke at the throat
    if actual_ratio < crit_ratio:
        # Sonic velocity at the throat
        T_throat = T0 * (2.0 / (gamma + 1.0))
        v_throat = np.sqrt(gamma * R_fluid * T_throat)
        
        # Supersonic expansion at outlet
        mach_out = np.sqrt(
            (2.0 / (gamma - 1.0)) * ((P_inlet / P_outlet)**((gamma-1.0)/gamma) - 1.0)
        )
        
        # Final exit velocity driving the MHD loop
        T_exit = T0 / (
            1.0 + 0.5 * (gamma - 1.0) * (mach_out ** 2)
        )
        v_exit = mach_out * np.sqrt(
            gamma * R_fluid * T_exit
        )
    else:
        # Standard subsonic expansion velocity
        v_exit = np.sqrt(
            (2.0 * gamma * R_fluid * T0 / (gamma - 1.0)) * (1.0 - (P_outlet / P_inlet)**((gamma - 1.0) / gamma))
        )

    print("--- NOZZLE KINETIC SIMULATION ---")
    print(f"Critical Ratio Limit: {crit_ratio:.3f}")
    print(f"Your Actual Ratio:   {actual_ratio:.3f}")
    if actual_ratio < crit_ratio:
        print("Flow Status:          CHOKED (SUPERSONIC)")
        print(f"Exit Mach Number:     M {mach_out:.2f}")
    else:
        print("Flow Status:          SUBSONIC")
    print(f"MHD Inlet Velocity:   {v_exit:.2f} m/s")
    print("---------------------------------")
    
    return v_exit

if __name__ == "__main__":
    # Test values using a modest pressure drop 
    # generated by 55°C server exhaust vaporization
    simulate_nozzle_expansion(
        P_inlet=150000.0,   # 1.5 Bar pressure absolute
        P_outlet=101325.0,  # 1.0 Bar atmospheric pressure
        T_exhaust=55.0,     # 55°C Exhaust source
        throat_diam=0.0015  # 1.5 mm throat specification
    )

